import { PageTop,PageBottom } from "@fileforge/react-print";

export const BillingInvoice = ({ details }) => {
  const { month, year, units, amount } = details;

  return (
    <div>
      <PageTop>
        <h1 className="text-2xl font-bold">Invoice</h1>
        <p className="text-sm">Date: {new Date().toLocaleDateString()}</p>
      </PageTop>
      <div className="mt-4">
        <p><strong>Month:</strong> {month}</p>
        <p><strong>Year:</strong> {year}</p>
        <p><strong>Units Used:</strong> {units}</p>
        <p><strong>Amount Paid:</strong> ₹{amount}</p>
      </div>
      <PageBottom>
        <p className="text-sm text-gray-500">Generated by My Account</p>
      </PageBottom>
    </div>
  );
};
